### ISSUE TITLE
<aspectLibraries> config is very lenient

### ISSUE THREAD

**Issue by zuckel** [dev-aspectj/aspectj-maven-plugin#111]
It seems that the plugin (dev.aspectj:aspectj-maven-plugin: 1.13.1) doesn't care at all what the elements inside of `<aspectLibraries>` are called.

This
```
<aspectLibraries>
    <aspectLibrary>
        <groupId>org.agroup</groupId>
        <artifactId>to-weave</artifactId>
    </aspectLibrary>
</aspectLibraries>
```
works just the same as this
```
<aspectLibraries>
    <toast>
        <groupId>org.agroup</groupId>
        <artifactId>to-weave</artifactId>
    </toast>
</aspectLibraries>
```

That's not a "problem" per se, but it doesn't feel right and it can lead to inconsistencies with other tools or in the future.

The Eclipse m2e-ajdt connector, for example, silently skips anything but `<aspectLibrary>` nodes.
This can lead to problems that are difficult to pin down because they depend on which tool did the last compilation. It took me quite a while to understand where my problems were coming from.

Enforcing the elements to be called `<aspectLibrary>` would be nice, but may be too strict for existing projects. But maybe it's possible to emit a warning if other names are detected.

**Comment by kriegaex** [comment]
Well, that is not an effect specific to AJ Maven Plugin. In general, sub-element naming for array parameters is not enforced in the Maven plugin API. It would be nice to have an additional `@Parameter` parameter to indicate the desired sub-element name, but there is none. You can try the same thing e.g. in Maven Surefire:

```xml
<plugin>
<artifactId>maven-surefire-plugin</artifactId>
<configuration>
  <excludes>
    <exclude>**/MyFirstTest.java</exclude>
    <toast>**/MySecondTest.java</toast>
  </excludes>
</configuration>
</plugin>
```

The plugin will not complain and just use the `toast` exclude normally.
