### ISSUE TITLE
Cannot build using Java9+

### ISSUE THREAD

**Issue by bmarwell** [dev-aspectj/aspectj-maven-plugin#5]
https://github.com/bmarwell/aspectj-maven-plugin/actions/runs/881364653

e.g.
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-site) on project aspectj-maven-plugin: failed to get report for org.codehaus.mojo:cobertura-maven-plugin: Plugin org.codehaus.mojo:cobertura-maven-plugin:2.6 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/../lib/tools.jar -> [Help 1]
```

Guess: hard dependency on `tools.jar` instead of using `ToolProvider`.
JDK9+ changed layouts.

**Comment by bmarwell** [comment]
Removed the system dependency, and it will still work. The ITs will fail, though.
Will add a PR later.

**Comment by kriegaex** [comment]
This is not happening in current GitHub builds here in this project. I am closing the issue. Please reopen, if you think I made a mistake and there is indeed an issue.
