### ISSUE TITLE
Any intention to support Java14+ ?

### ISSUE THREAD

**Issue by CyborTronik** [dev-aspectj/aspectj-maven-plugin#92]

**Comment by kriegaex** [comment]
What are you talking about? The plugin supports Java 18.

**Comment by CyborTronik** [comment]
This is what I get for Java 17:
```
[ERROR] Failed to execute goal dev.aspectj:aspectj-maven-plugin:1.13.1:compile (default) on project logging: AJC compiler errors:
[ERROR] error invalid source option: 17
[ERROR] error no sources specified
[ERROR] abort AspectJ Compiler
```

**Comment by CyborTronik** [comment]
This is the config:
```

                <plugin>
                    <groupId>dev.aspectj</groupId>
                    <artifactId>aspectj-maven-plugin</artifactId>
                    <version>1.13.1</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>compile</goal>
                                <goal>test-compile</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.aspectj</groupId>
                            <artifactId>aspectjtools</artifactId>
                            <version>${aspectj.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
```

**Comment by CyborTronik** [comment]
Updated dependencies and manually and works fine now...

**Comment by kriegaex** [comment]
There is no need to upgrade dependencies, unless you downgraded them before, because 1.13.1 automatically depends on AspectJ Tools 1.9.8.RC1, which is already Java 17 compliant. You must have used something like 1.9.7 or older, overrriding the default. But as you already found out, it is not a plugin problem but a usage problem if you manually select an AspectJ version too old to support Java 17. At present, the current version is 1.9.9.1, which supports Java 18. You want to use it like this:

```xml
<properties>
  <maven.compiler.source>17</maven.compiler.source>
  <maven.compiler.target>17</maven.compiler.target>
  <aspectj.version>1.9.7</aspectj.version>
</properties>

<build>
  <plugins>
    <plugin>
      <groupId>dev.aspectj</groupId>
      <artifactId>aspectj-maven-plugin</artifactId>
      <version>1.13.1</version>
      <executions>
        <execution>
          <goals>
            <goal>compile</goal>
            <goal>test-compile</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <source>${maven.compiler.source}</source>
        <target>${maven.compiler.target}</target>
      </configuration>
      <dependencies>
        <dependency>
          <groupId>org.aspectj</groupId>
          <artifactId>aspectjtools</artifactId>
          <version>${aspectj.version}</version>
        </dependency>
      </dependencies>
    </plugin>
  </plugins>
</build>

<dependencies>
  <dependency>
    <groupId>org.aspectj</groupId>
    <artifactId>aspectjrt</artifactId>
    <version>${aspectj.version}</version>
  </dependency>
</dependencies>
```

**Comment by kriegaex** [comment]
> So please consider to reopen it

No. The ticket was and is invalid, and besides: If your issue consists of just a cheeky subject line like "Any intention to support Java14+ ?" without even a single sentence of explanation or any [MCVE](https://stackoverflow.com/help/mcve), even if you would have found a real issue or concluded correctly that the Java version you fancy is unsupported (which is not true in this case), it would not be a good way to raise an issue.

**Comment by kriegaex** [comment]
I forgot to point you to a potentially helpful resource wich is also linked off the [AspectJ GitHub main page](https://github.com/eclipse/org.aspectj):

[AspectJ Java version compatibility table](https://github.com/eclipse/org.aspectj/blob/master/docs/dist/doc/JavaVersionCompatibility.md)

I hope this helps you to avoid future misunderstandings, enjoying both AspectJ and AspectJ Maven with a little less confusion. 😉
